### ISSUE TITLE
Document Preparation

### ISSUE THREAD

**Issue by mustafaberkay** [SE315-G3/main#1]
Ezgi Hazal Mergen - System Features - **Priority (5) / Difficulty (5) / Modifier (6)**
Mustafa Berkay (PM) - Introduction and overall description - **Priority (5) / Difficulty (5) / Modifier (6)**
Onat Çipli - Non-functional requirements - **Priority(5) / Difficulty (5) / Modifier (6)**
Mirkan Çalışkan - Interface requirements - **Priority (5) / Difficulty (6) / Modifier (6)**
@koguz @onatcipli @mirkancal @hazalmergen

**Comment by hazalmergen** [comment]
[System Features.docx](https://github.com/SE315-G3/main/files/855245/System.Features.docx)

**Comment by mustafaberkay** [comment]
[grup 3 SE 315 SRS document.pdf](https://github.com/SE315-G3/main/files/856592/grup.3.SE.315.SRS.document.pdf)

**Comment by mustafaberkay** [comment]
[grup 3 SE 315 SRS document (1).pdf](https://github.com/SE315-G3/main/files/856598/grup.3.SE.315.SRS.document.1.pdf)

**Comment by koguz** [comment]
[commented.grup.3.SE.315.SRS.document.1.pdf](https://github.com/SE315-G3/main/files/860539/commented.grup.3.SE.315.SRS.document.1.pdf)

I cannot approve this document. It is very badly written, it has grammar, spelling and other mistakes. Please read every comment I've written.

Also, your setup does not work for me. Who did what in this task? The manager should give well defined tasks.

**Comment by hazalmergen** [comment]
[Software Requirements.pdf](https://github.com/SE315-G3/main/files/871070/Software.Requirements.pdf)

**Comment by hazalmergen** [comment]
Updated version of SRS document.
[Software Requirements.pdf](https://github.com/SE315-G3/main/files/871072/Software.Requirements.pdf)

**Comment by koguz** [comment]
There is very little to change. Thank you. No update required. Approved.
