### ISSUE TITLE
News

### ISSUE THREAD

**Issue by mirkancal** [SE315-G3/main#8]
We have 5 new **issues** related to #SoftwareDesign 
You can sign your names on which task you aspire to do, simply by changing the **ContributorName** with your name. Don't forget the drag the cards on **Finished Tasks** after you've finished them.
Please don't hesitate to **ask any questions** or **sharing your ideas** under that **comment**.
Wish you all good luck!
@mustafaberkay @hazalmergen @onatcipli

**Comment by hazalmergen** [comment]
I can define and document the interfaces between our components that we seperated.

**Comment by mustafaberkay** [comment]
I can define the main objectives of the system

**Comment by onatcipli** [comment]
I can decide on and document third-party libraries.
